# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="createcomputers"
version="${file.jarVersion}"
displayName="CreateComputers"
credits="The ExampleMod dev team"
authors="ExampleModAuthor"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.createcomputers]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createcomputers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createcomputers]]
    modId = "computercraft"
    mandatory = true
    versionRange = "[1.100.9,)"
    ordering = "NONE"
    side = "BOTH"